version: "3"

networks:
  http_network:
    external: true

services:
  1mpose:
    image: makidelille/1posetonanonymat:latest
    restart: unless-stopped
  deploy:
    labels:
      - traefik.enable=true
      - traefik.frontend.rule=Host:1posetonanonymat.fr
      - traefik.port=3000
      - traefik.docker.network=http_network
    volumes:
      - ./img:/app/img
