version: "3"

networks:
  http_network:
    external: true

services:
  impose:
    image: makidelille/1posetonanonymat:latest
    restart: unless-stopped
    networks:
      - http_network
    deploy:
      labels:
        - traefik.enable=true
        - traefik.frontend.rule=Host:1posetonanonymat.fr
        - traefik.port=3000
        - traefik.docker.network=http_network
    volumes:
      - ./img:/app/img
